FROM python:3.11-slim

#VER LOGS EN TIEMPO REAL
ENV PYTHONUNBUFFERED=1
# Set working directory
WORKDIR /crud

# Copy requirements file if you have one
#INSTALA DEPENDENCIAS:
COPY requirements.txt .

# Install dependencies
 RUN pip install --no-cache-dir -r requirements.txt

# CopIA CODIGO FUENTE
COPY crud/ *
# COPY . .

# Command to run your app (replace with your entrypoint)

 CMD ["python", "manage.py","runserver","0.0.0.0.8000"]