# Generated by Django 5.2.5 on 2025-08-31 06:16

import oficina.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='nombre_corto',
            field=models.CharField(help_text='Codigo corto unico. (ej: PER,ADM,etc)', max_length=10, unique=True, validators=[oficina.models.validate_nombre_corto], verbose_name='id corto'),
        ),
    ]
