# Generated by Django 5.2.5 on 2025-08-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_alter_oficina_nombre_corto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficina',
            options={'verbose_name': 'Oficina', 'verbose_name_plural': 'oficinas'},
        ),
    ]
