# Generated by Django 5.2.5 on 2025-08-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre y apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo Electronico')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
