# Generated by Django 5.2.5 on 2025-10-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_alter_oficina_options'),
        ('persona', '0002_persona_oficina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='oficina.oficina', verbose_name='oficina asignada'),
        ),
    ]
